### ISSUE TITLE
[Request] Consider porting to webextension 

### ISSUE THREAD

**Issue by FatOrangutan** [JustOff/proxy-privacy-ruler#1]
Hello,

Please consider porting the add-on to a webextension so that it can continue working in Firefox 57 and beyond.

Thank you.

**Comment by JustOff** [comment]
WebExtensions do not provide all the necessary APIs to make this possible, so if you need in Proxy Privacy Ruler (or any other powerful classic add-ons) you should consider to switch to another XUL-based browser such as Pale Moon or SeaMonkey.
