### ISSUE TITLE
Browser hangs on DocShell links with "Limit Proxy by Domain List" enabled

### ISSUE THREAD

**Issue by Halibut80** [JustOff/proxy-privacy-ruler#2]
STR:

1. Create new clean profile and install Proxy Privacy Ruler 1.1.6

2. Enable "Limit Proxy by Domain List"

3. Open, for example, [https://github.com/gorhill/uBlock/releases](https://github.com/gorhill/uBlock/releases) and click any downloads link

4. Browser hangs

Win 8.1 x64, Firefox ESR 52.1.2 (64-bit),  Proxy Privacy Ruler 1.1.6, same with e10s enabled/disabled.
Issue does not occurs with PPR 1.1.5

**Comment by JustOff** [comment]
Confirmed, thanks for reporting it.

**Comment by JustOff** [comment]
Resolved by https://github.com/JustOff/proxy-privacy-ruler/commit/eb8432f72ceed141953c8220a954a03ac46f78d9.

**Comment by JustOff** [comment]
Still hangs, more investigation is required.

**Comment by JustOff** [comment]
False alarm, that was the fix.
