### ISSUE TITLE
[Suggestion] FQDN support in "Domain List"

### ISSUE THREAD

**Issue by Halibut80** [JustOff/proxy-privacy-ruler#3]
For now is need to double domain name with and without dot at the end. (e.g., ```example.com;example.com.```)

**Comment by JustOff** [comment]
> For now is need to double domain name

For what purpose?

**Comment by Halibut80** [comment]
Для поддержки RFC? :)
Некоторые плохо настроенные DPI тоже не следуют RFC и это был простой способ обходить блокировки. У меня просто имеются записи в истории/закладки и т.п. с точкой в конце и приходится теперь дублировать правила в списке доменов.

**Comment by JustOff** [comment]
Ага, т.е. закончить regexp `\.?$` вместо `$`?

**Comment by Halibut80** [comment]
Да, спасибо, было бы замечательно.

**Comment by JustOff** [comment]
Resolved by https://github.com/JustOff/proxy-privacy-ruler/commit/24bb23ce8e985c03de02d0e40677a0d534b69713.
