### ISSUE TITLE
[Suggestion/Bug] Ignore wrong parameters in "Domain List"

### ISSUE THREAD

**Issue by Halibut80** [JustOff/proxy-privacy-ruler#4]
Put ```*.onion``` to "Domain List" textbox.
All request, for now, will be forced to proxy.
Error from browser console:
```TypeError: domRegex is null  bootstrap.js:17:2```

**Comment by JustOff** [comment]
I agree, more accurate verification is necessary. I'll put this in todo list.

**Comment by JustOff** [comment]
Resolved by https://github.com/JustOff/proxy-privacy-ruler/commit/928ad7b93eaeb3446f1fd4b36b78448d72206efc.
