### ISSUE TITLE
[Suggestion] Wildcard/REGEXP support for domain list

### ISSUE THREAD

**Issue by Halibut80** [JustOff/proxy-privacy-ruler#5]
For example, I would like to force all request to onion-sites or to top-level domain to proxy, with something like: ```.onion;.ru``` or ```*.onion;*.ru```

**Comment by JustOff** [comment]
As of PPR 1.1.8 subdomains are always match, i.e. `onion` corresponds both `onion` and `*.onion`

**Comment by Halibut80** [comment]
Hm, this does not work for me.
```.onion```:

<a href="https://lh3.googleusercontent.com/-3dCFcQj0B7s/WS8Y1F-cAoI/AAAAAAAAdak/DsF2xuaQJ6QdoNjj_nZk2FfC81fsXC79gCHM/s0/screenshot%2B2017-05-31%2B001.png"><img src="https://lh3.googleusercontent.com/-NEPdNu3Xc7k/WS8Y1rHSFiI/AAAAAAAAdao/zhD2evdPgBsnsWe8P7PhcJHS_Ea3Uxl_gCHM/s0/thumb_d2bc79b6dcd54ee1d0e6b924c18e32c5.jpg" border=0></a><br/>&nbsp;<br/>
```nnmclub5toro7u65.onion```:

<a href="https://lh3.googleusercontent.com/-a5qSMN-LZLg/WS8Y21K9nrI/AAAAAAAAdas/i3UdGhUwKHUZsm8pfh3KWqLClevs5o5GwCHM/s0/screenshot%2B2017-05-31%2B002.png"><img src="https://lh3.googleusercontent.com/-X8AWt93oBlw/WS8Y3QdwEyI/AAAAAAAAdaw/WNJP8dojxu4dIabqZORj0jp3wzdjDcj6wCHM/s0/thumb_dd8b286535c03eae2294e2ba36678911.jpg" border=0></a><br/>&nbsp;<br/>
