### ISSUE TITLE
[Suggestion/Bug] Non ASCII domains support

### ISSUE THREAD

**Issue by Halibut80** [JustOff/proxy-privacy-ruler#6]
For now, all non ASCII domains, in domain list, are silently ignored.

(Maybe, as easy solution https://github.com/bestiejs/punycode.js)

**Comment by JustOff** [comment]
Resolved by https://github.com/JustOff/proxy-privacy-ruler/commit/1d326734126483fa069d9bce8e09084adbb5b084.

**Comment by JustOff** [comment]
Please verify using [1.2.0b1](https://addons.mozilla.org/en-US/firefox/addon/proxy-privacy-ruler/versions/1.2.0b1).

**Comment by Halibut80** [comment]
Does not work when network.IDN_show_punycode;true

**Comment by JustOff** [comment]
Yes, you are right and it's easy to fix, but for performance reason I would rather mention this in add-on description than add extra code to handle.

**Comment by Halibut80** [comment]
Ok, personally I always use punycode, so this is not really problem for me. Thank you.

**Comment by JustOff** [comment]
1.2.0 now on AMO.
